name: Build Flatpak

on:
  push:
    paths:
      - 'flumi/**'
      - '.github/workflows/build-flumi.yml'
      - '.github/workflows/build-flatpak.yml'
  pull_request:
    paths:
      - 'flumi/**'
      - '.github/workflows/build-flumi.yml'
      - '.github/workflows/build-flatpak.yml'
  workflow_dispatch:

jobs:
  pack:
    name: Package a Flatpak
    runs-on: ubuntu-24.04

    steps:
      - name: Download Flumi artifacts
        if: github.event.inputs.download_artifacts == 'true' || github.event_name == 'push'
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-flumi.yml
          name_is_regexp: true
          name: flumi-.*
          path: artifacts/
      - name: Download Flatpak and builder
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Set up package directory
        run: |
          mkdir -p FlumiFlatpak/bin
          cp artifacts/flumi-linux/* FlumiFlatpak/bin
          cat > manifest.json <<'EOF'
          {
            "id": "com.outpoot.Flumi",
            "runtime": "org.gnome.Platform",
            "runtime-version": "49",
            "sdk": "org.gnome.Sdk",
            "command": "Flumi",
            "modules": [
              {
                "name": "flumi",
                "buildsystem": "simple",
                "sources": [
                  {
                    "type": "dir",
                    "path": "FlumiFlatpak/bin"
                  }
                ],
                "build-commands": [
                  "install -D Flumi /app/bin/Flumi",
                  "install -D Flumi.pck /app/bin/Flumi.pck",
                  "install -D libgdluau.linux.template_release.x86_64.so /app/bin/libgdluau.linux.template_release.x86_64.so",
                  "install -D libgodot-flexbox.linux.template_release.x86_64.so /app/bin/libgodot-flexbox.linux.template_release.x86_64.so",
                  "install -D libgurt_godot.so /app/bin/libgurt_godot.so"
                ]
              }
            ]
          }
          EOF
      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install fp manifest.json
          flatpak build-bundle repo flumi.flatpak com.outpoot.Flumi --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: flatpak
          path: flumi.flatpak
          
          
